name = "lomeyolabs-com"
compatibility_date = "2024-01-01"

[build]
command = "npm install --legacy-peer-deps && npm run build"
output_directory = ".next"

[site]
bucket = "./.next"

[env.production]
name = "lomeyolabs-com-prod"

[env.staging]
name = "lomeyolabs-com-staging"