name = "lomeyolabs-com"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_directory = "out"

[site]
bucket = "./out"

[env.production]
name = "lomeyolabs-com-prod"

[env.staging]
name = "lomeyolabs-com-staging"